##################################################################################################
# greeter-client services
##################################################################################################
kind: ServiceAccount
apiVersion: v1
metadata:
  name: greeter-client
  namespace: greetings

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: greeter-client
  namespace: greetings
  labels:
    app: greeter-client
    app.kubernetes.io/name: greeter-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      serviceAccountName: greeter-client
      terminationGracePeriodSeconds: 0
      containers:
        - name: frontend
          image: greeter_client:local
        - name: frontend-go-instrumentation
          image: otel-go-agent:v0.1
          env:
          - name: OTEL_TARGET_EXE
            value: /app/greeter_client
          - name: OTEL_EXPORTER_OTLP_ENDPOINT
            value: otel-collector:4317
          - name: OTEL_SERVICE_NAME
            value: greeter_client
          - name: OTEL_PROPAGATORS
            value: "tracecontext,baggage"
          securityContext:
            runAsUser: 0
            capabilities:
              add:
                - SYS_PTRACE
            privileged: true
